// Eleventy configuration for the Axe Capital website.
// Pages live in src/, copy lives in src/_data, photography in src/assets/masters.
export default function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy({ "src/css": "css", "src/js": "js", "src/img": "img", "src/assets/favicon.svg": "favicon.svg", "src/assets/fonts": "fonts" });
  eleventyConfig.addWatchTarget("src/css");
  eleventyConfig.addWatchTarget("src/js");

  // Responsive <picture> for a photograph declared in src/assets/photos.json.
  // Sizes are generated by `npm run images` into src/_data/imageManifest.json.
  eleventyConfig.addShortcode("picture", function (id, alt = "", options = {}) {
    const manifest = this.ctx?.imageManifest || this.page?.data?.imageManifest;
    const entry = manifest && manifest[id];
    if (!entry) throw new Error(`Unknown image "${id}". Run \`npm run images\` first.`);
    const { loading = "lazy", sizes = "100vw", className = "" } = options;
    const [fx, fy] = entry.focus;
    const set = (list, ext) => list.map((s) => `/img/${s[ext]} ${s.width}w`).join(", ");
    const largest = entry.landscape[entry.landscape.length - 1];
    const portraitMedia = "(max-width: 767px) and (orientation: portrait)";
    const priority = loading === "eager" ? ` fetchpriority="high"` : "";
    const cls = className ? ` class="${className}"` : "";
    return `<picture${cls}>` +
      `<source type="image/avif" media="${portraitMedia}" sizes="100vw" srcset="${set(entry.portrait, "avif")}">` +
      `<source type="image/webp" media="${portraitMedia}" sizes="100vw" srcset="${set(entry.portrait, "webp")}">` +
      `<source type="image/avif" sizes="${sizes}" srcset="${set(entry.landscape, "avif")}">` +
      `<source type="image/webp" sizes="${sizes}" srcset="${set(entry.landscape, "webp")}">` +
      `<img src="/img/${largest.jpg}" srcset="${set(entry.landscape, "jpg")}" sizes="${sizes}" width="${entry.width}" height="${entry.height}" alt="${alt.replace(/"/g, "&quot;")}" loading="${loading}" decoding="async"${priority} style="object-position:${fx}% ${fy}%;background-image:url(${entry.placeholder})">` +
      `</picture>`;
  });

  eleventyConfig.addGlobalData("buildYear", () => new Date().getFullYear());
  eleventyConfig.addFilter("startsWith", (str, prefix) => typeof str === "string" && str.startsWith(prefix));

  return {
    dir: { input: "src", output: "_site", includes: "_includes", data: "_data" },
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
  };
}
